spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true